local backpack = game.Players.LocalPlayer.Backpack
local a = require(backpack["M4A1"].GunStates)
local b = require(backpack["Remington 870"].GunStates)
local c = require(backpack["AK-47"].GunStates)
local d = require(backpack["M9"].GunStates)
a.CurrentAmmo = math.huge
a.StoredAmmo = math.huge
a.FireRate = 0
a.Range = math.huge
a.ReloadTime = math.huge
a.AutoFire = true
a.MaxAmmo = math.huge
b.CurrentAmmo = math.huge
b.StoredAmmo = math.huge
b.FireRate = 0
b.Range = math.huge
b.ReloadTime = math.huge
b.AutoFire = true
b.MaxAmmo = math.huge
c.CurrentAmmo = math.huge
c.StoredAmmo = math.huge
c.FireRate = 0
c.Range = math.huge
c.ReloadTime = math.huge
c.AutoFire = true
c.MaxAmmo = math.huge
d.CurrentAmmo = math.huge
d.StoredAmmo = math.huge
d.FireRate = 0
d.Range = math.huge
d.ReloadTime = math.huge
d.AutoFire = true
d.MaxAmmo = math.huge
